### ISSUE TITLE
Финальный проект

### ISSUE THREAD

**Issue by marina-cyber** [Davabbb/TimeSeries#11]
1. Или я не поняла ваш код, или SMAPE считается неверно. 
Посмотрите  https://en.wikipedia.org/wiki/Symmetric_mean_absolute_percentage_error

2. Разложение на компоненты рядов - выглядит некорректным. Нужно подобрать окно, пока явно не так распадаются ряды.

3. Ну R2 отрицательное - с этим надо что-то делать. Тем более на реккурентных нейронках.
Вопрос не в количестве эпох обучения. А возможно - в структуре нейронки, и плохо очищенных/отфильтрованных  рядах.

**Comment by Davabbb** [comment]
я сделал

**Comment by marina-cyber** [comment]
R2 норм. Но получено для одного ряда.
по 1 и 2 пунктам - замечания остаются без изменений.

**Comment by marina-cyber** [comment]
На основе результатов теста причинности, попробуйте сформулировать причину плохих метрик для wind_speed. Расскажете.
